version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: pr-reviewer-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: pr_reviewer
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d pr_reviewer"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always
    volumes:
      - pg_data:/var/lib/postgresql/data

  migrator:
    image: gomicro/goose
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./internal/infrastructure/db/migrations:/migrations
    environment:
      GOOSE_DRIVER: postgres
      GOOSE_DBSTRING: postgres://user:password@postgres:5432/pr_reviewer?sslmode=disable
    command: ["goose", "-dir", "/migrations", "up"]

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      ENV: "docker"
      HTTP_ADDRESS: "0.0.0.0:8080"
      PG_URL: postgres://user:password@postgres:5432/pr_reviewer?sslmode=disable
    depends_on:
      postgres:
        condition: service_healthy
      migrator:
        condition: service_completed_successfully
    restart: on-failure

volumes:
  pg_data: